ambiance settings:
  port: 8080
  album: Home
  artist: Ambiance
  duration range:
  - 15
  - 30
  event range:
  - 8
  - 10
  volume: 2
  operation time:
    start: 9
    end: 20
device settings:
  Bedroom:
    enabled: False # Removes the device from the automation
  Bathroom:
    enabled: False # Removes the device from the automation
schedule:
track blacklist:
track weight: